### PR TITLE
Deprecation and cosmetic fixes

### PR DESCRIPTION
**Pull request by rlex**
Hello! This PR:

1) Will fix all (i hope, hasn't tested on RHEL) deprecation warnings, mostly caused by tests as filters

2) Adjust j2 bird template so it won't produce excessive whitelines in blocks, just for cleaner look.

I tested it on ubuntu 18.04.

### CODE REVIEW

**Comment by rlex** [comment]
Sadly, it will break ansible <2.3
One failed check is probably due to download.opensuse.org server issues

**Comment by logan2211** [comment]
Thanks! It looks good to me. I'm traveling for ansiblefest today but I want to briefly test the template change, so bear with me a few days please.

Also I'm fine with requiring 2.4, would you mind bumping the minimum version in `meta/main.yml` to 2.4 and removing the 2.3 tests?

I also just re-ran the suse tests that failed, hopefully the mirror issue is worked out now.

**Comment by rlex** [comment]
Any idea why it fails on 2.5?

**Comment by rlex** [comment]
Any updates?

**Comment by logan2211** [comment]
Merged your fixes in #29. Sorry for the delay-- it seemed like ansible didn't like something about your change to the test playbook includes, but that is no longer a problem because I converted the role to use the molecule testing framework. Thanks again for the PR!

**Pull request closed without merging**
